# NumPy Arrays


In [2]:
import numpy as np
my_list = [1,2,3]
my_list

[1, 2, 3]

In [6]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [7]:
my_mat =[[1,2,3],[3,4,5]]
np.array(my_mat)

array([[1, 2, 3],
       [3, 4, 5]])

In [12]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
## evenly space 10 numbers
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [28]:
## Identity Matrics
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
##within 0 and 1
np.random.rand(5)

array([0.42420671, 0.90776306, 0.9902577 , 0.12628039, 0.18049295])

In [26]:
np.random.rand(5,3)

array([[0.10636585, 0.31349645, 0.56357078],
       [0.34610551, 0.26114385, 0.17509612],
       [0.2248825 , 0.19707079, 0.47981753],
       [0.56640921, 0.0730625 , 0.45687226],
       [0.20380305, 0.78929597, 0.98714791]])

In [33]:
np.random.randn(3)

array([-0.31693665,  0.01039043, -0.36588536])

In [34]:
np.random.randint(1,100)

14

In [35]:
np.random.randint(1,100,10)

array([55,  7, 58, 28, 92, 51, 37, 64,  3, 64])

In [38]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 5, 31, 18, 49, 47, 32, 35, 47, 33, 43])

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arr.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [48]:
ranarr.max()

49

In [49]:
ranarr.min()

5

In [50]:
ranarr.argmax()

3

In [52]:
arr.shape

(25,)

In [ ]:
arr.dtype


# NumPy Indexing And Selection

In [8]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[1]

1

In [12]:
arr[1:5]

array([1, 2, 3, 4])

In [14]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [16]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [22]:
slice_of_arr[:]  = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
## Python not keep copies 
## If you need to have a copy
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr_2d = np.array([[5,10,15],[20,25,10],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 10],
       [35, 40, 45]])

In [31]:
arr_2d[0][0]

5

In [33]:
arr_2d[0]

array([ 5, 10, 15])

In [34]:
arr_2d[1,2]

10

In [37]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 10]])

In [39]:
##conditional Selection
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [44]:
## conditionally select elements from original array
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [46]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

# Numpy Operations

In [48]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [51]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [53]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [54]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [56]:
arr/arr

C:\Users\Akalanka\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [57]:
1/arr

C:\Users\Akalanka\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [59]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [61]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [62]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [63]:
np.max(arr)

10

In [64]:
np.min(arr)

0

In [65]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [66]:
np.log(arr)

C:\Users\Akalanka\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])