# NumPy Arrays


In [2]:
import numpy as np
my_list = [1,2,3]
my_list

[1, 2, 3]

In [6]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [7]:
my_mat =[[1,2,3],[3,4,5]]
np.array(my_mat)

array([[1, 2, 3],
       [3, 4, 5]])

In [12]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
## evenly space 10 numbers
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [28]:
## Identity Matrics
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
##within 0 and 1
np.random.rand(5)

array([0.42420671, 0.90776306, 0.9902577 , 0.12628039, 0.18049295])

In [2]:
np.random.rand(5,3)

NameError: name 'np' is not defined

In [33]:
np.random.randn(3)

array([-0.31693665,  0.01039043, -0.36588536])

In [34]:
np.random.randint(1,100)

14

In [35]:
np.random.randint(1,100,10)

array([55,  7, 58, 28, 92, 51, 37, 64,  3, 64])

In [38]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 5, 31, 18, 49, 47, 32, 35, 47, 33, 43])

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arr.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [48]:
ranarr.max()

49

In [49]:
ranarr.min()

5

In [50]:
ranarr.argmax()

3

In [52]:
arr.shape

(25,)

In [ ]:
arr.dtype


# NumPy Indexing And Selection

In [8]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])